// data.js — contenido bilingüe (ES/EN) para el kiosk del tótem.
// Strings de UI + FAQ con respuestas y fuentes simuladas.

window.KIOSK_STRINGS = {
  es: {
    locale: "es-AR",
    brandSuffix: "Autoservicio",
    // attract
    attract_greeting: "Hola, soy Vera",
    attract_sub: "Tu asistente del Galicia. Estoy para ayudarte.",
    attract_cta: "Tocá la pantalla para empezar",
    attract_hint: "Disponible las 24 horas",
    // home
    home_title: "¿Con qué te puedo ayudar?",
    home_sub: "Elegí una opción o hacé tu consulta por voz.",
    mod_faq_t: "Consultas y preguntas",
    mod_faq_d: "Tasas, horarios, tarjetas, sucursales y más.",
    mod_faq_a: "Preguntar",
    mod_voice_t: "Hablar con Vera",
    mod_voice_d: "Hacé tu consulta por voz y te respondo en pantalla.",
    mod_voice_a: "Tocá para hablar",
    mod_branches_t: "Sucursales y cajeros",
    mod_branches_d: "Encontrá la sucursal más cercana y sus horarios.",
    mod_branches_a: "Ver mapa",
    mod_help_t: "Atención humana",
    mod_help_d: "Te conecto con un representante por videollamada.",
    mod_help_a: "Conectar",
    cta_0800: "Llamar al 0800-333-1254",
    cta_0800_note: "Atención 24hs",
    // faq
    faq_title: "Consultas frecuentes",
    faq_placeholder: "Escribí tu pregunta…",
    faq_suggest: "Preguntas frecuentes",
    faq_listening: "Escuchando…",
    faq_listening_sub: "Hablá ahora, te estoy escuchando.",
    faq_thinking: "Buscando en galicia.ar…",
    faq_source: "Fuente",
    faq_speak_hint: "Vera está leyendo la respuesta",
    faq_ask_another: "Hacer otra consulta",
    faq_was_useful: "¿Te resultó útil?",
    faq_mic_tap: "Tocá el micrófono para hablar",
    faq_talk_cta: "¿Tu pregunta no está? Hablá con Vera",
    emg_slide: "Deslizá para pedir ayuda",
    voice_idle_title: "Preguntame lo que quieras",
    voice_idle_sub: "Tocá el micrófono y hablá, o elegí una pregunta.",
    voice_general: "Preguntas frecuentes",
    voice_listening: "Escuchando…",
    voice_thinking: "Buscando en galicia.ar…",
    voice_mic_tap: "Tocá para hablar",
    voice_mic_stop: "Tocá para terminar",
    voice_hear_you: "Te escucho…",
    voice_processing: "Entendido, buscando respuesta…",
    voice_no_match: "No entendí bien, ¿podés repetirlo?",
    voice_repeat: "Repetir",
    // keyboard
    kb_space: "espacio",
    kb_send: "Enviar",
    kb_123: "123",
    kb_abc: "ABC",
    // panic
    panic_label: "Emergencia",
    panic_hold: "Botón de pánico",
    panic_sent_title: "Alerta enviada",
    panic_sent_sub: "Nuestro equipo fue notificado. Serás atendido por un asistente en breve.",
    panic_stay: "Quedate en un lugar seguro y visible.",
    panic_id: "Tótem",
    panic_loc: "Ubicación",
    panic_time: "Hora del aviso",
    panic_status: "Estado",
    panic_status_active: "Asistente en camino",
    panic_cancel: "Fue un error — cancelar alerta",
    panic_canceling: "Cancelando…",
    // operator (vision)
    op_badge: "Vista del operador",
    op_alert_title: "Posible persona caída detectada",
    op_alert_sub: "El módulo de visión detectó una postura horizontal sostenida.",
    op_confidence: "Confianza",
    op_duration: "Duración detectada",
    op_frame_note: "Frame capturado · rostro difuminado por privacidad",
    op_ack: "Atender alerta",
    op_false: "Falsa alarma",
    op_dispatch: "Enviar personal",
    op_acked: "Alerta atendida — personal en camino",
    // footer
    footer_secure: "Conexión segura",
    back: "Volver",
    home: "Inicio",
  },
  en: {
    locale: "en-US",
    brandSuffix: "Self-service",
    attract_greeting: "Hi, I'm Vera",
    attract_sub: "Your Galicia assistant. I'm here to help.",
    attract_cta: "Touch the screen to begin",
    attract_hint: "Available 24 hours",
    home_title: "How can I help you?",
    home_sub: "Pick an option or ask me by voice.",
    mod_faq_t: "Questions & answers",
    mod_faq_d: "Rates, hours, cards, branches and more.",
    mod_faq_a: "Ask",
    mod_voice_t: "Talk to Vera",
    mod_voice_d: "Ask by voice and I'll answer on screen.",
    mod_voice_a: "Tap to talk",
    mod_branches_t: "Branches & ATMs",
    mod_branches_d: "Find the nearest branch and its hours.",
    mod_branches_a: "View map",
    mod_help_t: "Human support",
    mod_help_d: "I'll connect you with an agent by video call.",
    mod_help_a: "Connect",
    cta_0800: "Call 0800-333-1254",
    cta_0800_note: "24h support",
    faq_title: "Frequent questions",
    faq_placeholder: "Type your question…",
    faq_suggest: "Frequent questions",
    faq_listening: "Listening…",
    faq_listening_sub: "Go ahead, I'm listening.",
    faq_thinking: "Searching galicia.ar…",
    faq_source: "Source",
    faq_speak_hint: "Vera is reading the answer",
    faq_ask_another: "Ask another question",
    faq_was_useful: "Was this helpful?",
    faq_mic_tap: "Tap the microphone to speak",
    faq_talk_cta: "Question not here? Talk to Vera",
    emg_slide: "Slide to call for help",
    voice_idle_title: "Ask me anything",
    voice_idle_sub: "Tap the microphone and speak, or pick a question.",
    voice_general: "Frequent questions",
    voice_listening: "Listening…",
    voice_thinking: "Searching galicia.ar…",
    voice_mic_tap: "Tap to talk",
    voice_mic_stop: "Tap to finish",
    voice_hear_you: "I'm listening…",
    voice_processing: "Got it, searching for the answer…",
    voice_no_match: "I didn't quite catch that, can you repeat?",
    voice_repeat: "Repeat",
    kb_space: "space",
    kb_send: "Send",
    kb_123: "123",
    kb_abc: "ABC",
    panic_label: "Emergency",
    panic_hold: "Panic button",
    panic_sent_title: "Alert sent",
    panic_sent_sub: "Our team has been notified. An assistant will attend to you shortly.",
    panic_stay: "Stay in a safe, visible place.",
    panic_id: "Kiosk",
    panic_loc: "Location",
    panic_time: "Alert time",
    panic_status: "Status",
    panic_status_active: "Assistant on the way",
    panic_cancel: "It was a mistake — cancel alert",
    panic_canceling: "Cancelling…",
    op_badge: "Operator view",
    op_alert_title: "Possible fallen person detected",
    op_alert_sub: "The vision module detected a sustained horizontal posture.",
    op_confidence: "Confidence",
    op_duration: "Detected duration",
    op_frame_note: "Captured frame · face blurred for privacy",
    op_ack: "Acknowledge",
    op_false: "False alarm",
    op_dispatch: "Dispatch staff",
    op_acked: "Alert acknowledged — staff on the way",
    footer_secure: "Secure connection",
    back: "Back",
    home: "Home",
  },
};

// FAQ entries. q/a/source per language.
window.KIOSK_FAQ = [
  {
    id: "horarios",
    icon: "clock",
    keywords: "horario horarios hora hora cuando abren cierran abre cierra atienden atiende abierto cerrado sucursal sucursales dias laborales feriado funciona disponible",
    es: {
      q: "¿Cuál es el horario de atención?",
      a: "Las sucursales del Galicia atienden de lunes a viernes de 10:00 a 15:00 hs. Los cajeros automáticos y las terminales de autoservicio están disponibles las 24 horas, todos los días. La atención por la app y la web es permanente.",
      source: "galicia.ar / Atención al cliente",
    },
    en: {
      q: "What are the opening hours?",
      a: "Galicia branches are open Monday to Friday from 10:00 to 15:00. ATMs and self-service terminals are available 24 hours, every day. App and web support is always on.",
      source: "galicia.ar / Customer support",
    },
  },
  {
    id: "tarjeta",
    icon: "card",
    keywords: "tarjeta tarjetas perdi perdida robaron robo robada bloquear bloqueo bloqueá extravio extraviada credito debito plastico reponer reposicion denunciar denuncia robe",
    es: {
      q: "Perdí mi tarjeta, ¿qué hago?",
      a: "Podés bloquearla al instante desde la app del Galicia, en Tarjetas → Bloquear, o llamando al 0810-888-5454 las 24 horas. Una vez bloqueada, gestionás la reposición sin costo desde la misma app o en cualquier sucursal.",
      source: "galicia.ar / Tarjetas y seguridad",
    },
    en: {
      q: "I lost my card, what do I do?",
      a: "You can block it instantly from the Galicia app, under Cards → Block, or by calling 0810-888-5454, 24 hours. Once blocked, you can request a free replacement from the app or any branch.",
      source: "galicia.ar / Cards & security",
    },
  },
  {
    id: "plazofijo",
    icon: "growth",
    keywords: "plazo fijo plazofijo invertir inversion inversiones interes interes tasa rendimiento ahorrar ahorro guardar plata pesos colocar deposito constituir vencimiento",
    es: {
      q: "¿Cómo hago un plazo fijo?",
      a: "Podés constituir un plazo fijo en pesos desde la app o el home banking, sin mínimo de apertura y eligiendo el plazo desde 30 días. La tasa se confirma en el momento de la constitución y el dinero se acredita automáticamente al vencimiento.",
      source: "galicia.ar / Inversiones",
    },
    en: {
      q: "How do I open a fixed-term deposit?",
      a: "You can open a peso fixed-term deposit from the app or online banking, with no minimum and terms from 30 days. The rate is confirmed at the moment you open it and funds are credited automatically at maturity.",
      source: "galicia.ar / Investments",
    },
  },
  {
    id: "prestamo",
    icon: "wallet",
    keywords: "prestamo prestamos credito creditos pedir sacar plata dinero financiacion cuotas preaprobado preaprobada monto necesito dinero presta prestan",
    es: {
      q: "¿Puedo sacar un préstamo personal?",
      a: "Si tenés un préstamo preaprobado, lo ves en la app en Préstamos → Mi oferta y el dinero se acredita al instante en tu cuenta. El monto y la cantidad de cuotas dependen de tu perfil crediticio. No tiene gastos de otorgamiento.",
      source: "galicia.ar / Préstamos",
    },
    en: {
      q: "Can I get a personal loan?",
      a: "If you have a pre-approved loan, you'll see it in the app under Loans → My offer and the money is credited instantly to your account. Amount and installments depend on your credit profile. There are no origination fees.",
      source: "galicia.ar / Loans",
    },
  },
  {
    id: "cuenta",
    icon: "user",
    keywords: "cuenta cuentas abrir crear alta nueva caja ahorro cbu cliente hacerme hacer asociarme apertura registrarme dni online",
    es: {
      q: "¿Cómo abro una cuenta?",
      a: "Abrir una Cuenta Galicia es 100% online y gratis: descargá la app, validá tu identidad con tu DNI y una selfie, y en pocos minutos tenés tu CBU y tu tarjeta digital lista para usar. No necesitás ir a la sucursal.",
      source: "galicia.ar / Cuentas",
    },
    en: {
      q: "How do I open an account?",
      a: "Opening a Galicia account is 100% online and free: download the app, verify your identity with your ID and a selfie, and within minutes you'll have your account number and a digital card ready to use. No branch visit needed.",
      source: "galicia.ar / Accounts",
    },
  },
  {
    id: "transferir",
    icon: "send",
    keywords: "transferir transferencia transferencias enviar mandar plata dinero limite limites tope giro pasar girar cbu cvu alias inmediata",
    es: {
      q: "¿Hay límite para transferir dinero?",
      a: "Las transferencias entre cuentas propias no tienen límite. Para transferencias a terceros, el límite diario inicial es configurable desde la app en Seguridad → Límites. Las transferencias por CBU/CVU/alias son inmediatas y sin costo.",
      source: "galicia.ar / Transferencias",
    },
    en: {
      q: "Is there a limit to transfer money?",
      a: "Transfers between your own accounts have no limit. For transfers to third parties, the initial daily limit is configurable in the app under Security → Limits. Transfers by account number or alias are instant and free.",
      source: "galicia.ar / Transfers",
    },
  },
];
